# Generated by Django 2.1.7 on 2019-05-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
