# Generated by Django 2.1.7 on 2019-06-04 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_item_order_orderlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderList',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
