# Generated by Django 2.1.7 on 2019-06-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Tech', 'Technology'), ('Access', 'Accessories'), ('Trans', 'Transportation'), ('Misc', 'Other')], default='Misc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'new'), ('H', 'hot'), ('D', 'danger')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
